apiVersion: v1
kind: Service
metadata:
  name: python-demoapp-service
spec:
  selector:
    app: python-demoapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

