apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-demoapp
  template:
    metadata:
      labels:
        app: python-demoapp
    spec:
      containers:
      - name: python-demoapp
        image: ghcr.io/benc-uk/python-demoapp:latest
        ports:
        - containerPort: 5000

